# FROM nginx:1.21.6

# COPY ./nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
# ADD ./cert/localhost+1.pem /etc/certs/localhost.pem
# ADD ./cert/localhost+1-key.pem /etc/certs/localhost-key.pem