


# version: '3'

# services:
      
#   db:
#     platform: linux/x86_64 # Mac M1対応
#     image: mysql:5.7
#     volumes:
#       - db_data:/var/lib/mysql
#     environment:
#       MYSQL_DATABASE: ${MYSQL_DATABASE}
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_USER: ${MYSQL_USER}
#       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#     restart: always

#   nginx:
#     platform: linux/x86_64 # Mac M1対応
#     # build: ./resources
#     image: nginx:latest
#     ports:
#       - "${NGINX_HOST}:80"
#       - "${NGINX_SSL}:443" # "mkcert localhost 127.0.0.1"で証明書を発行している状態
#     volumes:
#       - ./src/${DIR_NAME}/${PROJECT_NAME}:/var/www/html
#       - ./resources/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#       - ./resources/cert/localhost+1.pem:/etc/certs/localhost.pem
#       - ./resources/cert/localhost+1-key.pem:/etc/certs/localhost-key.pem
#     depends_on:
#       - wordpress
#     restart: always

#   wordpress:
#     image: wordpress:php7.4-fpm
#     volumes:
#       - ./src/${DIR_NAME}/${PROJECT_NAME}:/var/www/html
#     expose:
#       - "9000"
#     environment:
#       WORDPRESS_DB_HOST: db:3306 # mysqlコンテナを指定
#       WORDPRESS_DB_USER: ${MYSQL_USER} # MYSQL_USERと合わせる
#       WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD} # MYSQL_PASSWORDと合わせる
#       WORDPRESS_DB_NAME: ${MYSQL_DATABASE} # MYSQL_DATABASEと合わせる
#     depends_on:
#       - db
#     restart: always

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     restart: always
#     depends_on:
#       - db
#     ports:
#       - ${PHPMYADMIN_HOST}:80

# volumes:
#   db_data: