version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_HOST}:80"
      - "${NGINX_SSL}:443" # "mkcert localhost 127.0.0.1"で証明書を発行している状態
    volumes:
      - ./dist:/var/www/html
      - ./resources/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./resources/cert/localhost+1.pem:/etc/certs/localhost.pem
      - ./resources/cert/localhost+1-key.pem:/etc/certs/localhost-key.pem
    depends_on:
      - php7.4
    restart: always

  php7.4:
    build: ./resources/php
    volumes:
      - ./dist:/var/www/html
    depends_on:
      - db
    restart: always

  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      # - db_data:/var/lib/mysql
      - ./resources/mysql57/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - ${PHPMYADMIN_HOST}:80
    depends_on:
      - db
    restart: always

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "${SMTP_CONFIRM}:1080"
      - "${SMTP_PORT}:1025"
      
# volumes:
#   db_data: