version: '3'

services:
      
  db:
    platform: linux/x86_64 # Mac M1対応
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE     : ${MYSQL_DATABASE} # WORDPRESS_DB_NAMEと合わせる
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}      # ルートパスワード
      MYSQL_USER         : ${MYSQL_USER}    # WORDPRESS_DB_USERと合わせる
      MYSQL_PASSWORD     : ${MYSQL_PASSWORD}      # WORDPRESS_DB_PASSWORDと合わせる
    restart: always

  nginx:
    platform: linux/x86_64 # Mac M1対応
    # build: ./resources
    image: nginx:1.21.6
    ports:
      - "${NGINX_HOST}:80"
      - "${NGINX_SSL}:443"
    volumes:
      - ./src/${DIR_NAME}/${PROJECT_NAME}:/var/www/html
      - ./resources/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./resources/cert/localhost+1.pem:/etc/certs/localhost.pem
      - ./resources/cert/localhost+1-key.pem:/etc/certs/localhost-key.pem
    depends_on:
      - wordpress # wordpress起動後でないとnginxがnot foundで落ちる
    restart: always

  wordpress:
    image: wordpress:php7.4-fpm
    volumes:
      - ./src/${DIR_NAME}/${PROJECT_NAME}:/var/www/html
    expose:
      - "9000"
    environment:
      WORDPRESS_DB_HOST     : db:3306     # mysqlコンテナを指定
      WORDPRESS_DB_USER     : ${MYSQL_USER}    # MYSQL_USERと合わせる
      WORDPRESS_DB_PASSWORD : ${MYSQL_PASSWORD}      # MYSQL_PASSWORDと合わせる
      WORDPRESS_DB_NAME     : ${MYSQL_DATABASE} # MYSQL_DATABASEと合わせる
    depends_on:
      - db
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    ports:
      - ${PHPMYADMIN_HOST}:80

volumes:
  db_data:



# version: '3'

# services:
#    db:
#      platform: linux/x86_64 # Mac M1対応
#      image: mysql:5.7
#      volumes:
#        - db_data:/var/lib/mysql
#      restart: always
#      environment:
#        MYSQL_ROOT_PASSWORD: root_wordpress
#        MYSQL_DATABASE: wordpress
#        MYSQL_USER: wordpress
#        MYSQL_PASSWORD: wordpress

#    wordpress:
#      depends_on:
#        - db
#      image: wordpress:latest
#     #  working_dir: /var/www/html/
#      ports:
#        - "${WP_HOST}:80"
#      restart: always
#      environment:
#        WORDPRESS_DB_HOST: db:3306
#        WORDPRESS_DB_USER: wordpress
#        WORDPRESS_DB_PASSWORD: wordpress
#      volumes:
#        - ./src/${DIR_NAME}/${PROJECT_NAME}:/var/www/html

#    phpmyadmin:
#     image: phpmyadmin/phpmyadmin:latest
#     restart: always
#     depends_on:
#       - db
#     ports:
#       - ${PHPMYADMIN_HOST}:80

# volumes:
#     db_data: