version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_HOST}:80"
      - "${NGINX_SSL}:443" # "mkcert localhost 127.0.0.1"で証明書を発行している状態
    volumes:
      # - ./src/${WORKING_DIR}/${PROJECT_DIR}:/var/www/html
      - ./src:/var/www/html
      - ./resources/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./resources/cert/localhost+1.pem:/etc/certs/localhost.pem
      - ./resources/cert/localhost+1-key.pem:/etc/certs/localhost-key.pem
    depends_on:
      - php7.4
    restart: always

  php7.4:
    build: ./resources/php
    volumes:
      # - ./src/${WORKING_DIR}/${PROJECT_DIR}:/var/www/html
      - ./src:/var/www/html
    depends_on:
      - mysql
    restart: always

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${PHPMYADMIN_HOST}:80
    depends_on:
      - mysql5.7
    restart: always

volumes:
  db_data: